### ISSUE TITLE
[Umbrella-Item] Make WinForms DataBinding Apps trimmable

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#10741]
This is an investigation and prototype issue at this point (with some good prospects of success, though).

- [ ] Investigate options to improve Designer-side code generation to support Trimming for WinForms App which use Designer-hooked-up Data Binding (we will *explicitly* exclude non-type-safe Data Binding, like Runtime-Binding to DataTables/DataViews which use Property Descriptors to create "Types" at runtime.)
- [ ] Investigate runtime API-Improvements around
  - [ ] [Binding](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/DataBinding/Binding.cs,bed1e5beea29de5c)
  - [ ] [BindingSource](https://source.dot.net/#q=BindingSource)
  - [ ] [Formatter](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Internal/Formatter.cs,e12c083610518727)
  - [ ] [ListBindingHelper](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/DataBinding/ListBindingHelper.cs,cdf058a848f1cd26)
  - [ ] [ListBindingConverter](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/DataBinding/ListBindingConverter.cs,b89feeecce85a487)
  - [ ] [BindingList<T>](https://source.dot.net/#System.ComponentModel.TypeConverter/System/ComponentModel/BindingList.cs,55afabf0a74c12cc)

**Comment by merriemcgaw** [comment]
I'm super excited to see how this goes!
