### ISSUE TITLE
Review: all editors derived from UITypeEditor ported

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1115]
As suggested in https://github.com/dotnet/winforms/issues/892#issuecomment-495455585 review whether [all editors derived from `UITypeEditor`](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.design.uitypeeditor?view=netframework-4.8) have been ported:

### Remaining: If there is a customer demand we can port these, but if not we can postpone or skip them.
* [x] ~**ColumnHeaderCollectionEditor**, System.Windows.Forms.Design (#2334 )~
* [x] ~[DataGridViewComponentEditor](https://github.com/dotnet/winforms/search?q=DataGridViewComponentEditor&unscoped_q=DataGridViewComponentEditor) (#2335)~
* [x] ~[DataGridViewCellStyleEditor](https://github.com/dotnet/winforms/search?q=DataGridViewCellStyleEditor&unscoped_q=DataGridViewCellStyleEditor) (#2347)~
* [x] [DataGridViewColumnDataPropertyNameEditor](https://github.com/dotnet/winforms/search?q=DataGridViewColumnDataPropertyNameEditor&unscoped_q=DataGridViewColumnDataPropertyNameEditor) (#2337)
* [x] [DataMemberListEditor](https://github.com/dotnet/winforms/search?q=DataMemberListEditor&unscoped_q=DataMemberListEditor) (#2338)
* [x] [DataMemberFieldEditor](https://github.com/dotnet/winforms/search?q=DataMemberFieldEditor&unscoped_q=DataMemberFieldEditor) (#2339) (#12891 )
* [x] **StyleCollectionEditor**, System.Windows.Forms.Design (#2340)
* [x] **ToolStripCollectionEditor**, System.Windows.Forms.Design (#2341)
* [x] [ToolStripImageIndexEditor](https://github.com/dotnet/winforms/search?q=ToolStripImageIndexEditor&unscoped_q=ToolStripImageIndexEditor) (#2342)
* [x] **TreeNodeCollectionEditor**, System.Windows.Forms.Design (#2343)
* [x] ~**TreeNodeStyleCollectionEditor**, System.Windows.Forms.Design (#2344)~ this one applies to web controls
* [x]  ~**[ControlBindingsConverter](https://github.com/dotnet/winforms/issues/12966)**~  This issue is on hold until customer requests are received.
* [x] **[DataGridViewColumnCollectionEditor](https://github.com/dotnet/winforms/issues/12954)** #12925

### 3.1:
* [x] **BinaryEditor** System.ComponentModel.Design, System.Design.dll (#2123)
* [x] **ContentAlignmentEditor** System.Drawing.Design, System.Drawing.Design.dll (#2117)
* [x] **DateTimeEditor** System.ComponentModel.Design, System.Design.dll (#2165)
* [x] **ListControlStringCollectionEditor**, System.Windows.Forms.Design (https://github.com/dotnet/winforms/pull/2078)
* [x] **ListViewGroupCollectionEditor**, System.Windows.Forms.Design (#2196)
* [x] **ListViewItemCollectionEditor**, System.Windows.Forms.Design (#2197)
* [x] **ListViewSubItemCollectionEditor**, System.Windows.Forms.Design (#2198)
* [x] [ImageIndexEditor](https://github.com/dotnet/winforms/search?q=ImageIndexEditor&unscoped_q=ImageIndexEditor) (#2116)
* [x] **IconEditor** System.Drawing.Design, System.Drawing.Design.dll (#2089)
* [x] **TabPageCollectionEditor**, System.Windows.Forms.Design (#2118)
* [x] WIP [LinkAreaEditor](https://github.com/dotnet/winforms/search?q=LinkAreaEditor&unscoped_q=LinkAreaEditor) (#2284 )
* [x] [MaskPropertyEditor](https://github.com/dotnet/winforms/search?q=MaskPropertyEditor&unscoped_q=MaskPropertyEditor) (#2285 )
* [x] [MaskedTextBoxTextEditor](https://github.com/dotnet/winforms/search?q=MaskedTextBoxTextEditor&unscoped_q=MaskedTextBoxTextEditor) (#2286 )
* [x] [SelectedPathEditor](https://github.com/dotnet/winforms/search?q=SelectedPathEditor&unscoped_q=SelectedPathEditor) (#2282 )
* [x] [HelpNamespaceEditor](https://github.com/dotnet/winforms/search?q=HelpNamespaceEditor&unscoped_q=HelpNamespaceEditor) (#2283 )
* [x] [FormatStringEditor](https://github.com/dotnet/winforms/search?q=FormatStringEditor&unscoped_q=FormatStringEditor) (#2281 )

### 3.0:
* [x] AnchorEditor
* [x] BorderSidesEditor
* [x] CollectionEditor
* [x] ColorEditor
* [x] CursorEditor
* [x] DockEditor
* [x] FileNameEditor
* [x] FolderNameEditor
* [x] FontEditor
* [x] FontNameEditor
* [x] ImageEditor
* [x] MultilineStringEditor
* [x] ObjectSelectorEditor
* [x] ShortcutKeysEditor
* [x] ~**ArrayEditor**, System.ComponentModel.Design~ (https://github.com/dotnet/winforms/pull/1181)
* [x] ~**StringCollectionEditor**, System.Windows.Forms.Design~ (https://github.com/dotnet/winforms/pull/1284)
* [x] ~**StringArrayEditor**, System.Windows.Forms.Design~ (https://github.com/dotnet/winforms/pull/1272)
* [x] ~**ImageCollectionEditor**, System.Windows.Forms.Design~ (https://github.com/dotnet/winforms/pull/1299)

### Won't be porting

Deprecated control ❗️ 
* [ ] ~[DataGridColumnStyleMappingNameEditor](https://github.com/dotnet/winforms/search?q=DataGridColumnStyleMappingNameEditor&unscoped_q=DataGridColumnStyleMappingNameEditor)~ 
* [ ] ~[DataGridTableStyleMappingNameEditor](https://github.com/dotnet/winforms/search?q=DataGridTableStyleMappingNameEditor&unscoped_q=DataGridTableStyleMappingNameEditor)~
* [ ] ~[DataGridColumnStyleFormatEditor](https://github.com/dotnet/winforms/search?q=DataGridColumnStyleFormatEditor&unscoped_q=DataGridColumnStyleFormatEditor)~
* [x] ~**DataGridColumnCollectionEditor**, System.Windows.Forms.Design~ (#2119) ⬅️ this serves deprecated `DataGrid` control ❗️ 
* [x] ~****StatusBarDesigner**(https://github.com/dotnet/docs/issues/17008)~

Messaging
* [ ] ~**QueuePathEditor** System.Messaging.Design, System.Messaging.dll~

Web
* [ ] ~**ConnectionStringEditor** System.Web.UI.Design, System.Design.dll~
* [ ] ~**DataControlFieldTypeEditor** System.Web.UI.Design.WebControls, System.Design.dll~
* [ ] ~**DataGridColumnCollectionEditor** System.Web.UI.Design.WebControls, System.Design.dll~
* [ ] ~**DataPagerFieldTypeEditor** System.Web.UI.Design.WebControls, System.Web.Extensions.Design.dll~
* [ ] ~**ExpressionsCollectionEditor** System.Web.UI.Design, System.Design.dll~
* [ ] ~**MenuBindingsEditor** System.Web.UI.Design.WebControls, System.Design.dll~
* [ ] ~**MenuItemCollectionEditor** System.Web.UI.Design.WebControls, System.Design.dll~
* [ ] ~**ParameterCollectionEditor** System.Web.UI.Design.WebControls, System.Design.dll~
* [ ] ~**RegexTypeEditor** System.Web.UI.Design.WebControls, System.Design.dll~
* [ ] ~**TreeNodeCollectionEditor** System.Web.UI.Design.WebControls, System.Design.dll~
* [ ] ~**TreeViewBindingsEditor** System.Web.UI.Design.WebControls, System.Design.dll~
* [ ] ~**UrlEditor** System.Web.UI.Design, System.Design.dll~
* [ ] ~**XmlFileEditor** System.Web.UI.Design, System.Design.dll~
* [ ] ~**DataGridDesigner** System.Web.UI.Design.WebControls, System.Design.dll~

### Obsolete
* [x] **BindUITypeEditor** System.Workflow.ComponentModel.Design, System.Workflow.ComponentModel.dll
* [x] **DataBindingCollectionEditor** System.Web.UI.Design, System.Design.dll
* [x] **TypeBrowserEditor** System.Workflow.ComponentModel.Design, System.Workflow.ComponentModel.dll
* [x] ~**IntegerCollectionEditor**, System.Windows.Forms.Design (https://github.com/dotnet/winforms/pull/1285)~ appears unused
* [x] ~****ToolBarButtonDesigner** (Replaced with [ToolStripButton](https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.forms.toolbarbutton?view=netframework-4.8.1))~
* [x] ~****ToolBarDesigner** (Replaced with [ToolStrip](https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.forms.toolbar?view=netframework-4.8.1))~

**Comment by RussKie** [comment]
@merriemcgaw need your help with prioritisation.

I think we only need to port these:
* **BinaryEditor** System.ComponentModel.Design, System.Design.dll
*  **ContentAlignmentEditor** System.Drawing.Design, System.Drawing.Design.dll
*  **DateTimeEditor** System.ComponentModel.Design, System.Design.dll
*  **IconEditor** System.Drawing.Design, System.Drawing.Design.dll

The web and messaging are outside our namespaces.

**Comment by merriemcgaw** [comment]
As much as I'd like this, I think we'll prioritize this a little lower and add these if/when we get customer requests for these editors. So I won't close this, but I'll punt it to future. I expect we will want them but I won't block 3.0 on it.

**Comment by RussKie** [comment]
It looks there are more missing editors, I missed those as they are internal:

* [] StringCollectionEditor, System.Windows.Forms.Design
* [] StringCollectionEditor, System.Windows.Forms.Design
* [] StringCollectionEditor, System.Windows.Forms.Design
* [] StringCollectionEditor, System.Windows.Forms.Design
* [] StringCollectionEditor, System.Windows.Forms.Design
* [] StringCollectionEditor, System.Windows.Forms.Design

**Comment by RussKie** [comment]
It looks there are more missing editors, I missed those as they are all `internal`:

Descendants of `CollectionEditor` (only in our namespaces):
* [] **ColumnHeaderCollectionEditor**, System.Windows.Forms.Design
* [] **DataGridColumnCollectionEditor**, System.Windows.Forms.Design
* [] **ImageCollectionEditor**, System.Windows.Forms.Design
* [] **IntegerCollectionEditor**, System.Windows.Forms.Design
* [] **ListViewGroupCollectionEditor**, System.Windows.Forms.Design
* [] **ListViewItemCollectionEditor**, System.Windows.Forms.Design
* [] **ListViewSubItemCollectionEditor**, System.Windows.Forms.Design
* [] **StringCollectionEditor**, System.Windows.Forms.Design
* [] **StyleCollectionEditor**, System.Windows.Forms.Design
* [] **TabPageCollectionEditor**, System.Windows.Forms.Design
* [] **ToolStripCollectionEditor**, System.Windows.Forms.Design
* [] **TreeNodeCollectionEditor**, System.Windows.Forms.Design

Descendants of `StringCollectionEditor` (only in our namespaces):
* [] **ListControlStringCollectionEditor**, System.Windows.Forms.Design
* [] **StringArrayEditor**, System.Windows.Forms.Design

Descendants of `StyleCollectionEditor` (only in our namespaces):
* [] **TreeNodeStyleCollectionEditor**, System.Windows.Forms.Design

**Comment by weltkante** [comment]
More missing editors:

- [ ] [DataMemberListEditor](https://github.com/dotnet/winforms/search?q=DataMemberListEditor&unscoped_q=DataMemberListEditor)
- [ ] [DataMemberFieldEditor](https://github.com/dotnet/winforms/search?q=DataMemberFieldEditor&unscoped_q=DataMemberFieldEditor)
- [ ] [ImageIndexEditor](https://github.com/dotnet/winforms/search?q=ImageIndexEditor&unscoped_q=ImageIndexEditor)
- [ ] [FormatStringEditor](https://github.com/dotnet/winforms/search?q=FormatStringEditor&unscoped_q=FormatStringEditor)
- [ ] [SelectedPathEditor](https://github.com/dotnet/winforms/search?q=SelectedPathEditor&unscoped_q=SelectedPathEditor)
- [ ] [HelpNamespaceEditor](https://github.com/dotnet/winforms/search?q=HelpNamespaceEditor&unscoped_q=HelpNamespaceEditor)
- [ ] [LinkAreaEditor](https://github.com/dotnet/winforms/search?q=LinkAreaEditor&unscoped_q=LinkAreaEditor)
- [ ] [MaskPropertyEditor](https://github.com/dotnet/winforms/search?q=MaskPropertyEditor&unscoped_q=MaskPropertyEditor)
- [ ] [MaskedTextBoxTextEditor](https://github.com/dotnet/winforms/search?q=MaskedTextBoxTextEditor&unscoped_q=MaskedTextBoxTextEditor)
- [ ] [ToolStripImageIndexEditor](https://github.com/dotnet/winforms/search?q=ToolStripImageIndexEditor&unscoped_q=ToolStripImageIndexEditor)

- [ ] [DataGridColumnStyleMappingNameEditor](https://github.com/dotnet/winforms/search?q=DataGridColumnStyleMappingNameEditor&unscoped_q=DataGridColumnStyleMappingNameEditor)
- [ ] [DataGridTableStyleMappingNameEditor](https://github.com/dotnet/winforms/search?q=DataGridTableStyleMappingNameEditor&unscoped_q=DataGridTableStyleMappingNameEditor)
- [ ] [DataGridColumnStyleFormatEditor](https://github.com/dotnet/winforms/search?q=DataGridColumnStyleFormatEditor&unscoped_q=DataGridColumnStyleFormatEditor)
- [ ] [DataGridViewComponentEditor](https://github.com/dotnet/winforms/search?q=DataGridViewComponentEditor&unscoped_q=DataGridViewComponentEditor)
- [ ] [DataGridViewCellStyleEditor](https://github.com/dotnet/winforms/search?q=DataGridViewCellStyleEditor&unscoped_q=DataGridViewCellStyleEditor)
- [ ] [DataGridViewColumnDataPropertyNameEditor](https://github.com/dotnet/winforms/search?q=DataGridViewColumnDataPropertyNameEditor&unscoped_q=DataGridViewColumnDataPropertyNameEditor)

<details><summary>found via</summary>

```C#
var map = new Dictionary<string, HashSet<string>>();

void Report(string subject, string editor)
{
    if (!map.TryGetValue(editor, out var list))
        map.Add(editor, list = new HashSet<string>());

    list.Add(subject);
}

foreach (var type in typeof(Control).Assembly.DefinedTypes)
{
    foreach (var editorAttr in type.GetCustomAttributes<EditorAttribute>())
        if (editorAttr != null && Type.GetType(editorAttr.EditorTypeName) == null)
            Report($"{type.Name}", editorAttr.EditorTypeName);

    foreach (var prop in type.DeclaredProperties)
    {
        foreach (var editorAttr in prop.GetCustomAttributes<EditorAttribute>())
            if (editorAttr != null && Type.GetType(editorAttr.EditorTypeName) == null)
                Report($"{type.Name}.{prop.Name}", editorAttr.EditorTypeName);
    }
}

foreach (var pair in map)
{
    Debug.WriteLine($"{pair.Key}");
    foreach (var x in pair.Value)
        Debug.WriteLine($"  {x}");
}
```

</details>

You probably should add a unit test which verifies that all editor attributes can be resolved.

**Comment by RussKie** [comment]
Thank you!

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - could you please organize work porting the remaining editors. We received requests to port some editors and expect to get more.
1. start with sources of System.Design.dll in the VS repo
2. edit and simplify source code according to our style guide (apply the analyzers to whole documents) and run the copilot review to get mechanical optimizations.
3. Make sure that the new editor can be invoked from the demo console integration test and works well (it would be helpful to get https://github.com/dotnet/winforms/issues/12830 finished first)
4. Work with Olina's team to get unit test PRs for the newly added editors soon after PR that ports the editor is merged.

**Comment by merriemcgaw** [comment]
We've got some use-cases that have surfaced and we understand the importance of bringing in the remaining designers. Looking into this for .NET 10 as APIs can't be added to shipped versions.

**Comment by Tanya-Solyanik** [comment]
The full list of missing components is here - https://github.com/dotnet/winforms/blob/e0da5a881a6269649d47939a4b2ee61ae04688b8/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs#L18-#L39

**Comment by LeafShi1** [comment]
[like]  Leaf Shi (BEYONDSOFT CONSULTIN... reacted to your message:
________________________________

**Comment by LeafShi1** [comment]
[like]  Leaf Shi (BEYONDSOFT CONSULTIN... reacted to your message:
________________________________

**Comment by LeafShi1** [comment]
According to the full list [here](https://github.com/dotnet/winforms/blob/e0da5a881a6269649d47939a4b2ee61ae04688b8/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs#L18-#L39), the following editors are missing from this issue

- [ ] **ControlBindingsConverter**
- [ ] ~****DataGridDesigner** ([Web control](https://devdiv.visualstudio.com/DevDiv/_git/DotNetFramework?path=/src/ndp/fx/src/xsp/System/Web/ui/WebControls/DataGrid.cs&_a=contents&version=GBmain))~
- [ ] **DataGridViewColumnCollectionEditor**
- [ ] ~****StatusBarDesigner**([deprecated control]((https://github.com/dotnet/docs/issues/17008)))~
- [ ] ~****ToolBarButtonDesigner** (Replaced with [ToolStripButton](https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.forms.toolbarbutton?view=netframework-4.8.1))~
- [ ] ~****ToolBarDesigner** (Replaced with [ToolStrip](https://learn.microsoft.com/zh-cn/dotnet/api/system.windows.forms.toolbar?view=netframework-4.8.1))~
