### ISSUE TITLE
Epic - [Accessibility] Implement UIA provider for all controls

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#3421]
* Base issue: #2146
* Base PR: #3037 

* .NET Core Version: 6.0

**Problem description:**
- Many .Net Core WinForms controls support `MSAA` proxy, which is unmanaged for us. These controls don't support `UIA` provider. This doesn't allow us to change some Accessibility properties or methods to fix some Accessibility bugs. We can't manage our AccessibleObjects fully.

**Expected behavior:**
- All .Net controls support UIA provider

**Minimal repro:**
- Create a .Net Winforms app
- Add any control to the MainForm
- Check `ProviderDescription` Accessibility property of this control using Inspect

## Controls
<details>
  <summary>Done</summary>

- [x]  Button (#3215)
- [x]  CheckBox (#3228)
- [x] ComboBox (#4540)
- [x] DataGridView
- [x] DataGridViewEditingPanel
- [x] DataGridViewTextBoxEditingControl
- [x] ErrorProvider (#2381)
- [x] DomainUpDown (#2382)
- [x] Form (#2096)
- [x] GroupBox 
- [x] Label (#3206)
- [x] ListBox (#935)
- [x] ListView (#3224)
- [x] MonthCalendar (#2090)
- [x] NumericUpDown (#2382)
- [x] PictureBox (#3233)
- [x] ProgressBar
- [x] PropertyGrid
- [x] DocComment
- [x] DropDownButton
- [x] HotCommands
- [x] PropertyGridView
- [x] DropDownHolder
- [x] GridViewEdit
- [x] PictureBox (#3233)
- [x] PropertyGridView
- [x] RadioButton (#3244)
- [x] Splitter (#3246)
- [x] StatusStrip
- [x] ToolStrip
- [x] ToolStripComboBoxControl
- [x] ToolStripNumericUpDownControl
- [x] ToolStripProgressBarControl
- [x] ToolStripTextBoxControl
- [x] UpDownButtons
- [x] ScrollBar/HScrollBar/VScrollBar (#5044)
- [x] TrackBar (#4939)
- [x] LinkLabel (#5157)
- [x] TabControl (#5380)
- [x] CheckedListBox (#5276)
- [x] Panel (#5485)
- [x] TabPage (#5380)
- [x] MenuStrip
- [x] ContextMenuStrip
- [x] DateTimePicker (#6620)
- [x] ToolStripContainer (#6568) (Danil Andrianov)
- [x] PrintPreviewControl (#6600)
- [x] SplitContainer (#6519) (Danil Andrianov)
- [x] FlowLayoutPanel (#5485) (Artem Tatarinov)
- [x] TreeView (#6432) (Dmitry Gorokhov)
- [x] TableLayoutPanel (#5485) (Artem Tatarinov)
- [x] ToolStripContentPanel (#5485) (Artem Tatarinov)
- [x] WebBrowser (#7314)
- [x] ToolStripPanel (#7459)
- [x] TextBox (#7741)
- [x] MaskedTextBox (#7741)

</details>

**In progress:**

<details>
  <summary>TODO</summary>

- [ ] RichTextBox

</details>

<details>
  <summary>In the future</summary>

- [ ] AxHost
- [ ] BindingNavigator
- [ ] ComponentEditorForm
- [ ] ComponentEditorPage
- [ ] GridErrorDlg
- [ ] GridToolTip
- [ ] MarshalingControl
- [ ] MdiClient
- [ ] MdiControlStrip
- [ ] MdiWindowDialog
- [ ] MdiWindowListStrip
- [ ] PrintControllerWithStatusDialog
- [ ] SendKeys
</details>

**Comment by merriemcgaw** [comment]
@RussKie  - let's take a look at Win32 docs about which UIA patterns are really needed on which controls.

**Comment by vladimir-krestov** [comment]
@merriemcgaw, if I got it correctly, we need to implement UIA for all controls to have correct navigation in the Accessibility hierarchy. We need it to fix #3037.

**Comment by RussKie** [comment]
In the 5.0 definitely:

* [ ] TextBoxBase

In the 5.0 maybe:

* [ ]  ListControl - abstract
* [ ]  MenuStrip


In the 6.0+:

* [ ]  ScrollBar
* [ ]  HScrollBar
* [ ]  VScrollBar
* [ ]  MaskedTextBox
* [ ]  DateTimePicker
* [ ]  UpDownBase - abstract
* [ ]  NumericUpDown
* [ ]  MenuStrip
* [ ]  FlowLayoutPanel

**Comment by elachlan** [comment]
@Tanya-Solyanik is this "Done"? Do we just have bugs remaining?
