### ISSUE TITLE
Support designer capabilities at runtime

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4908]
# Context

The Windows Forms SDK consist of two distinct parts – the **runtime** (the code that executes, open sourced in this repo) and the **designer** (consists of the "_general purpose_" and "_Visual Studio-specific_"  components, close sourced). In .NET Framework these two parts lived together, and that allowed customers to invoke and use VS-specific functionality. Skip forward to .NET Core/.NET and these two components are now split and evolve (for the most part) independently of each other.
 
The more and more customers are starting to migrate their apps to .NET the more we see the demand to the missing designer capabilities to be ported over to .NET (e.g. #1395, #2573, #4456, #4886, #4887, [AB#1314797](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1314797)).

# In scope:

However we need to port the general purpose designer infrastructure – i.e. API that enable building "_a designer that the user can embed in their application_". For example, a user might have a business application that contains a report designer feature, which can use our "general designer" framework.

* The following designers are currently available (though may have restricted or incomplete functionality):
  - [x] System.ComponentModel.Design.ComponentDesigner
  - [x] System.Windows.Forms.Design.DocumentDesigner (#122)
  - [x] System.Windows.Forms.Design.FormDocumentDesigner (#681)
  - [x] System.Windows.Forms.Design.MaskedTextBoxDesigner (#9709)
  - [x] System.Windows.Forms.Design.ParentControlDesigner (#122)
  - [x] System.Windows.Forms.Design.ScrollableControlDesigner (#122)
  - [x] System.Windows.Forms.Design.TextBoxBaseDesigner
  - [x] System.Windows.Forms.Design.ToolStripDesigner
  - [x] System.Windows.Forms.Design.ToolStripDropDownDesigner
  - [x] System.Windows.Forms.Design.ToolStripItemDesigner
  - [x] System.Windows.Forms.Design.ToolStripMenuItemDesigner
 
* The following designers are missing and will be ported in scope of #4860:
  - [x] System.Windows.Forms.Design.ButtonBaseDesigner
  - [x] System.Windows.Forms.Design.ControlDesigner
  - [x] System.Windows.Forms.Design.DocumentDesigner - functionality restored
  - [x] System.Windows.Forms.Design.LabelDesigner
  - [x] System.Windows.Forms.Design.ParentControlDesigner - functionality restored
  - [x] System.Windows.Forms.Design.ScrollableControlDesigner - functionality restored
  - [x] System.Windows.Forms.Design.TextBoxDesigner
  - [x] System.Windows.Forms.Design.ComboBoxDesigner
  - [x] System.Windows.Forms.Design.GroupBoxDesigner
  - [x] System.Windows.Forms.Design.ListBoxDesigner
  - [x] System.Windows.Forms.Design.ListViewDesigner
  - [x] System.Windows.Forms.Design.PanelDesigner
  - [x] System.Windows.Forms.Design.PictureBoxDesigner
  - [x] System.Windows.Forms.Design.RadioButtonDesigner
  - [x] System.Windows.Forms.Design.RichTextBoxDesigner
  - [x] System.Windows.Forms.Design.TreeViewDesigner
  - [x] System.Windows.Forms.Design.UpDownBaseDesigner
  - [x] System.Windows.Forms.Design.UserControlDocumentDesigner

# Open for consideration

The following API may be considered for porting upon significant demand and real use cases.

* The following designers:
  - [x] System.Windows.Forms.Design.DateTimePickerDesigner (#8549)
  - [x] System.Windows.Forms.Design.FlowLayoutPanelDesigner (#9658 9658)
  - [x] System.Windows.Forms.Design.MonthCalendarDesigner (#9536)
  - [x] System.Windows.Forms.Design.PrintDialogDesigner (#9595  )
  - [x] System.Windows.Forms.Design.TableLayoutPanelDesigner(#9560)
  - [x] System.Windows.Forms.Design.TabControlDesigner(#9560)
  - [x] System.Windows.Forms.Design.TabPageDesigner(#9560)
* Missing editors for the ported designers, see the list in #2411

# Out of scope

* Back-porting of the missing types in .NET Core 3.1 or .NET 5.0, because both of these are going out of support shortly after .NET 6.0 is released.
* The VS-specific designer functionality will not be made available, because it makes no sense outside the VS. 
* Databinding
* Advanced databinding designers and editors
* The following designers:
  - [x] System.Windows.Forms.Design.AxDesigner (Tracked with #9810)
  - [x] System.Windows.Forms.Design.AxHostDesigner  (Tracked with #9810)
  - [x] System.Windows.Forms.Design.BindingNavigatorDesigner(https://github.com/dotnet/winforms/pull/9749)
  - [x] System.Windows.Forms.Design.BindingSourceDesigner(https://github.com/dotnet/winforms/pull/9749)
  - [x] System.Windows.Forms.Design.DataGridViewColumnDesigner (https://github.com/dotnet/winforms/pull/9677)
  - [x] System.Windows.Forms.Design.DataGridViewComboBoxColumnDesigner (https://github.com/dotnet/winforms/pull/9869)
  - [x] System.Windows.Forms.Design.DataGridViewDesigner (https://github.com/dotnet/winforms/pull/9677)
  - [x] System.Windows.Forms.Design.FolderBrowserDialogDesigner (https://github.com/dotnet/winforms/pull/9682)
  - [x] System.Windows.Forms.Design.ImageListDesigner
  - [x] System.Windows.Forms.Design.NotifyIconDesigner (https://github.com/dotnet/winforms/pull/9645)
  - [x] System.Windows.Forms.Design.PropertyGridDesigner (https://github.com/dotnet/winforms/pull/9645)
  - [x] System.Windows.Forms.Design.SaveFileDialogDesigner (https://github.com/dotnet/winforms/pull/9682)
   <del>System.Windows.Forms.Design.StatusBarDesigner</del>
  - [x] System.Windows.Forms.Design.SplitContainerDesigner (https://github.com/dotnet/winforms/pull/9320)
  - [x] System.Windows.Forms.Design.SplitterDesigner (https://github.com/dotnet/winforms/pull/9320)
  - [x] System.Windows.Forms.Design.SplitterPanelDesigner (https://github.com/dotnet/winforms/pull/9320)
  - [x] System.Windows.Forms.Design.ToolStripContainerDesigner (https://github.com/dotnet/winforms/pull/9750)
  - [x] System.Windows.Forms.Design.ToolStripContentPanelDesigner (https://github.com/dotnet/winforms/pull/9750)
  - [x] System.Windows.Forms.Design.ToolStripPanelDesigner (https://github.com/dotnet/winforms/pull/9750)
  - [x] System.Windows.Forms.Design.TrackBarDesigner (https://github.com/dotnet/winforms/pull/9703)
  - [x] System.Windows.Forms.Design.WebBrowserDesigner (Tracked with #9810)

**Comment by RussKie** [comment]
- RESERVED -

**Comment by mansai** [comment]
NET 6.0 Support designer
 System.Windows.Forms.Design.DataGridViewDesigner

The VS-specific designer functionality will be made available, because it makes very sense outside the VS.

For example: User form Designer

**Comment by RussKie** [comment]
Please elaborate and explain a use case where VS-centric designers is required outside VS.

**Comment by merriemcgaw** [comment]
We are reopening this issue to collect requests for specific designers not yet implemented.

**Comment by dmitrii-drobotov** [comment]
https://github.com/dotnet/winforms/issues/8749 - SplitContainerDesigner 
https://github.com/dotnet/winforms/issues/8790 - TablelayoutPanelDesigner, TabControlDesigner

**Comment by LeafShi1** [comment]
@Tanya-Solyanik Currently four designers have not been ported.
Can we remove `AxDesigner `and `AxHostDesigner ` from the current Task?
The two controls are COM components. I tested these two designers according to the following steps, 

```
**Creating ActiveX Control in Windows Forms Application**

1. Create a new MFC ActiveX Control project with name

MFCActiveXControl. Click Finish on setting window and build MFCActiveXControl.

2. Get file MFCActiveXControl.ocx from the Debug folder.

**To registe an ActiveX control with ocx file**

1. Copy AxImp.exe from SDK path and the ocx file to a new folder c:\school for instance.

2. Open a Command Prompt as Administrator and run command line

regsvr32.exe c:\school\{ocx file name}.

In this test the command line is

“regsvr32.exe c:\school\MFCActiveXControl.ocx”.

3. Run command line cd c:\school to locate\\ the path of AxImp.exe and run command line AXImp.exe MFCActiveXControl.Ocx.

**To test the ActiveX control in Windows Forms Application**

1. Open project Prj1, add a Tab to Toolbox named AxtiveXControl. Right Click to select Choose Items…, and choose COM Components, select MFCActiveXControl, and click OK.

2. Drag the MFCActiveXControl to the Form.

3. Build and run.
```

but there are some problems when `Drag the MFCActiveXControl to the Form`. 
**.netFramework App**
![image](https://github.com/dotnet/winforms/assets/132890443/8e53b18b-783b-4fb1-a5b2-4edfc78272b1)

**.netcore app**
![image](https://github.com/dotnet/winforms/assets/132890443/3ff3404b-940a-4387-b6f3-591eae3a55c5)

And on the .Net Core designer, support for these two controls ([AxHost/COM Control support in designer](https://github.com/microsoft/winforms-designer/issues/4902), [Enable ActiveX Support](https://github.com/microsoft/winforms-designer/issues/815)) is still in progress. 

.Net Core designer doesn't support `StatusBarDesigner `and `WebBrowserDesigner`, do we need to port them from VS?

**Comment by Tanya-Solyanik** [comment]
1. ActiveX related designers can be done later. Please create a new bug for them. WebBrowser control is backed up by and ActiveX as well, so it will be covered by that bug as well. We will use that bug for tracking any user requests.
2. Since StatusBar control is deprecated, please cross out this designer from the list.

**Comment by Tanya-Solyanik** [comment]
Let's close this one again when all outstanding PRs are merged.

**Comment by LeafShi1** [comment]
> 1. ActiveX related designers can be done later. Please create a new bug for them. WebBrowser control is backed up by and ActiveX as well, so it will be covered by that bug as well. We will use that bug for tracking any user requests.
> 2. Since StatusBar control is deprecated, please cross out this designer from the list.

Track ActiveX related designers with issue #9810
