### ISSUE TITLE
Rewritten MAUI tests can't pass pipelines

### ISSUE THREAD

**Issue by Danil-Andrianov** [dotnet/winforms#6501]
* .NET Core Version: 
7.0.0-alpha.1.21576.4

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Some rewritten MAUI tests can't pass pipelines for some reasons. They're passing local build and staying successful for many reruns without any single fail. Unfortunately, in this case it's spoil debugging and for checking every test fix we should rerun pipelines, which many times less productive than rerun single problematic test locally. I suggest list of problematic tests below. The list could be updated in case of discovering new problematic tests.

- [ ] System.Windows.Forms.UITests.PrintPreviewDialogTests.PrintPreviewDialog_Hotkey_Ctrl_1Async (#8430)
- [ ] System.Windows.Forms.UITests.PrintPreviewDialogTests.PrintPreviewDialog_Hotkey_Ctrl_2Async (#8430)
- [ ] System.Windows.Forms.UITests.PrintPreviewDialogTests.PrintPreviewDialog_Hotkey_Ctrl_3Async (#8430)
- [ ] System.Windows.Forms.UITests.PrintPreviewDialogTests.PrintPreviewDialog_Hotkey_Ctrl_4Async (#8430)
- [ ] System.Windows.Forms.UITests.PrintPreviewDialogTests.PrintPreviewDialog_Hotkey_Ctrl_5Async (#8430)
- [x] System.Windows.Forms.UITests.ComboBoxTests.ComboBox_Select_Item_By_UpArrowKeyAsync (#7323)
- [x] System.Windows.Forms.Tests.PropertyGridView_PropertyGridViewAccessibleObjectTests.PropertyGridViewRowsAccessibleObject_Ctor_Default (#6405 )
