### ISSUE TITLE
Add unit tests to ToolboxItem and ComponentDesigner

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#714]
Add unit tests (if not exists) for

1) Methods:

System.Drawing.Design.ToolboxItem
- [x] M:System.Drawing.Design.ToolboxItem.#ctor(System.Type)
- [x] M:System.Drawing.Design.ToolboxItem.CreateComponents(System.ComponentModel.Design.IDesignerHost)
- [x] M:System.Drawing.Design.ToolboxItem.get_AssemblyName
- [x] M:System.Drawing.Design.ToolboxItem.get_Bitmap
- [x] M:System.Drawing.Design.ToolboxItem.get_DisplayName
- [x] M:System.Drawing.Design.ToolboxItem.get_TypeName
- [x] M:System.Drawing.Design.ToolboxItem.GetType(System.ComponentModel.Design.IDesignerHost)
- [x] M:System.Drawing.Design.ToolboxItem.set_DisplayName(System.String)

System.ComponentModel.Design.ComponentDesigner
- [x] M:System.ComponentModel.Design.ComponentDesigner.#ctor
- [x] M:System.ComponentModel.Design.ComponentDesigner.Dispose(System.Boolean)
- [x] M:System.ComponentModel.Design.ComponentDesigner.get_ActionLists
- [x] M:System.ComponentModel.Design.ComponentDesigner.get_AssociatedComponents
- [x] M:System.Windows.Forms.Design.ControlDesigner.AssociatedComponents #9516
- [x] M:System.Windows.Forms.Design.ListViewDesigner.AssociatedComponents #9516
- [x] M:System.Windows.Forms.Design.SplitContainerDesigner.AssociatedComponents #9516
- [x] M:System.Windows.Forms.Design.ToolStripDesigner.AssociatedComponents #9516
- [x] M:System.Windows.Forms.Design.ToolStripDropDownDesigner.AssociatedComponents #9575
- [x] M:System.Windows.Forms.Design.ToolStripDropDownItemDesigner.AssociatedComponents #9575
- [x] M:System.Windows.Forms.Design.ToolStripMenuItemDesigner.AssociatedComponents #9575
- [x] M:System.ComponentModel.Design.ComponentDesigner.get_Component
- [x] M:System.ComponentModel.Design.ComponentDesigner.get_InheritanceAttribute
- [x] M:System.ComponentModel.Design.ComponentDesigner.get_Verbs #9483 
- [x] M:System.ComponentModel.Design.ComponentDesigner.GetService(System.Type)#9483 
- [x] M:System.ComponentModel.Design.ComponentDesigner.Initialize(System.ComponentModel.IComponent)
- [x] M:System.ComponentModel.Design.ComponentDesigner.InitializeNewComponent(System.Collections.IDictionary)
- [x] M:System.ComponentModel.Design.ComponentDesigner.PostFilterProperties(System.Collections.IDictionary)#9483 
- [x] M:System.ComponentModel.Design.ComponentDesigner.PreFilterEvents(System.Collections.IDictionary)
- [x] M:System.ComponentModel.Design.ComponentDesigner.PreFilterProperties(System.Collections.IDictionary)
- [x] M:System.ComponentModel.Design.ComponentDesigner.RaiseComponentChanged(System.ComponentModel.MemberDescriptor,System.Object,System.Object)
- [x] M:System.ComponentModel.Design.ComponentDesigner.RaiseComponentChanging(System.ComponentModel.MemberDescriptor)

2) Classes:
- [x] System/Drawing/Design/ToolboxItemCollection.cs
<del>System/ComponentModel/Design/CodeMarkers.cs</del>
- [x] System/ComponentModel/Design/DesignerCommandSet.cs
- [x] System/ComponentModel/Design/InheritedPropertyDescriptor.cs

Epic: #716 
Related issues: #221, #469
Related PRs: #552, #480

**Comment by hughbe** [comment]
ToolboxItem/ToolboxItemCollection tests added

**Comment by hughbe** [comment]
ComponentDesigner tests also. I think this can be closed now

**Comment by hughbe** [comment]
Actually, missing tests for
- InheritedPropertyDescriptor

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 , @Epica3055 , @SimonZhao888  - the first step in this work item would be to determine what tests are already implemented and check them off in the list. Then feel free to break this issue into multiple PRs.

**Comment by Tanya-Solyanik** [comment]
Please remove CodeMarkers class as part of this work. This class is used in perf test in the VS, it provides access to code markers implemented in a VS assembly - "Microsoft.VisualStudio.CodeMarkers.dll", and thus is not pertinent to the runtime. It's an oversight that it is still in this codebase.

**Comment by Epica3055** [comment]
@Tanya-Solyanik 
ActionLists unit tests are covered in DesignerActionListTests.cs
AssociatedComponents are covered in other unit tests. But there are some classes that override it, should we test them?

**Comment by Tanya-Solyanik** [comment]
>But there are some classes that override it, should we test them?

Yes, please if these are internal (not private) classes. Also please update the table in the bug.
