### ISSUE TITLE
Add unit tests to System.Windows.Forms.Design.ControlDesigner

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#721]
Add unit tests (if not exists) for

1) Methods:
- [x] M:System.Windows.Forms.Design.ControlDesigner.#ctor
- [x] M:System.Windows.Forms.Design.ControlDesigner.get_SelectionRules

2) Classes:
- [x] System/ComponentModel/Design/DesignerActionListsChangedEventArgs.cs
- [ ] System/ComponentModel/Design/DesignerActionPanel.cs
- [ ] System/ComponentModel/Design/DesignerActionUIService.cs
- [ ] System/Windows/Forms/Design/BaseContextMenuStrip.cs
- [ ] System/Windows/Forms/Design/Behavior/ContainerSelectorBehavior.cs
- [ ] System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
- [ ] System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
- [ ] System/Windows/Forms/Design/Behavior/ResizeBehavior.cs
- [x] System/Windows/Forms/Design/ControlDesigner.cs
- [ ] System/Windows/Forms/Design/DesignerActionPanel.cs
- [ ] System/Windows/Forms/Design/DesignerActionService.cs
- [ ] System/Windows/Forms/Design/DesignerActionUI.cs
- [ ] System/Windows/Forms/Design/DesignerFrame.cs
- [ ] System/Windows/Forms/Design/DesignerUtils.cs
- [ ] System/Windows/Forms/Design/FormDocumentDesigner.cs
- [ ] System/Windows/Forms/Design/ParentControlDesigner.cs
- [ ] System/Windows/Forms/Design/SelectionManager.cs
- [ ] System/Windows/Forms/Design/ToolStripAdornerWindowService.cs
- [ ] System/Windows/Forms/Design/ToolStripDesigner.cs
- [ ] System/Windows/Forms/Design/ToolStripDesignerUtils.cs
- [ ] System/Windows/Forms/Design/ToolStripDropDownDesigner.cs
- [ ] System/Windows/Forms/Design/ToolStripDropDownItemDesigner.cs
- [ ] System/Windows/Forms/Design/ToolStripEditorManager.cs
- [ ] System/Windows/Forms/Design/ToolStripInSituService.cs
- [ ] System/Windows/Forms/Design/ToolStripItemBehavior.cs
- [ ] System/Windows/Forms/Design/ToolStripItemDesigner.cs
- [ ] System/Windows/Forms/Design/ToolStripKeyboardHandlingService.cs
- [x] System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs（PR: [9868](https://github.com/dotnet/winforms/pull/9868)）
- [ ] System/Windows/Forms/Design/ToolStripTemplateNode.cs

Epic: #716
Related issues: #221, #653
Related PRs: #681

**Comment by brucremo** [comment]
Hello @JuditRose! I would like to help build those unit tests, could I work on them?? Thanks in advance!

**Comment by RussKie** [comment]
@brucremo that's awesome! Please go ahead.

/cc: @hughbe

**Comment by LeafShi1** [comment]
Track this issue with #10773
