### ISSUE TITLE
[Tracking] CodeQL Bugs

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#8561]
- [x] [AB#1666874](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666874)
- [x] [AB#1666875](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666875)
- [x] ~[AB#1666876](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666876)~
- [x] [AB#1666878](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666878)
- [x] [AB#1666879](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666879)
- [x] ~[AB#1666880](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666880)~
- [x] ~[AB#1666882](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666882)~
- [x] ~[AB#1666883](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666883)~
- [x] ~[AB#1666895](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666895)~
- [x] ~[AB#1666897](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666897)~
- [x] [AB#1666899](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1666899)

**Comment by merriemcgaw** [comment]
Assigned remainder back to Levi. This effort is complete for now - will do bugs as they are manually assigned.
