### ISSUE TITLE
[Tracking] Update UI tests infra to make them reliable.

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#9318]
This is to track work required to enable UI tests again in the repo. Current strategy to send input via `SendInput `API seems unreliable and flaky. Tried to fix it with following experiments but didn't help.

- [x] Tried with increasing delays.
- [x] Made sure Application is idle before proceeding further.
- [x] Removed any other windows interfering with tests on build agents.
- [x] Moved to Sequential execution
- [x] Increased retries both at tests level and build level.
- [x] Ensured everything is being sent on UI thread.
- [x] Paused execution on ARM64 and also on Release branches
- [x] Paused execution of UI tests in internal CI builds.
- [x] Blocked UI tests from execution from everything as all steps above failed to achieve reliability.

- [ ]  Further investigation to make tests reliable. 

Pausing the UI tests execution until we fix these and achieve reliability either by replacing `SendInput` API or find a way to make it work reliably. This issue is to track the work needed.
